# Generated by Django 3.1.3 on 2021-01-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socila', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
