# Generated by Django 3.1.3 on 2021-01-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_auto_20210129_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
