# Generated by Django 3.1.3 on 2021-01-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20210129_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
